♻️ refactor: remove build-style.js and update storybook to v7.0
Candy-Doc/candy-doc-components-library pull request #43
Opened 2023-04-14 12:12 UTC by AntonyDerache

# Pull request for Candy-doc components library

## Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../../CONTRIBUTING.md) to
this repository.

- [X] Make sure you are requesting to **pull a feature/bugfix branch** (right
  side). Don't request your master!
- [X] Make sure you are making a pull request against the **main branch** (left
  side).
- [X] Check the commit's or even all commits' message styles matches our
  requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit
  test.

## Description

- Due to not working changes using unocss, it has been removed to use a new way of replacing build-style.
Injecting tailwind css into lit elements style to remove all css components files and build-style on the way.
- Storybook update to v7.0 lead to a depreciated type -> refactor all .stories to comply with the new type
- Global code cleaning/refactor in .stories and components
- Navigation and interactions in storybook has been improved 
</br>

❤️ Thank you!

2023-04-19 08:53 UTC, Yugo-Cartron approved these changes
That's good

2023-04-19 08:59 UTC, ctacquet submitted a review, later dismissed
Good job !

2023-05-16 14:00 UTC, Yugo-Cartron commented on src/components/Alert/Alert.ts
> +  static styles = [AlertStyle];
static styles = AlertStyle;

2023-05-16 14:02 UTC, Yugo-Cartron requested changes
You should keep the same energy bro

2023-05-16 14:09 UTC, Yugo-Cartron submitted a review, later dismissed
Very good job Anto !

2023-05-16 15:10 UTC, Yugo-Cartron approved these changes

2023-05-16 15:10 UTC, merged

2023-05-16 15:12 UTC, Tifloz commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [GitHub release](https://github.com/Candy-Doc/candy-doc-components-library/releases/tag/v1.6.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@candy-doc/ui/v/1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: