✨ feat(popover): add close icon
Candy-Doc/candy-doc-components-library pull request #75
Opened 2023-07-20 13:07 UTC by AntonyDerache

# Pull request for Candy-doc components library

## Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../../CONTRIBUTING.md) to
this repository.

- [X] Make sure you are requesting to **pull a feature/bugfix branch** (right
  side). Don't request your master!
- [X] Make sure you are making a pull request against the **main branch** (left
  side).
- [X] Check the commit's or even all commits' message styles matches our
  requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit
  test.

## Description

Add a small cross icon to at the top right of popover to close it on click

Enhance UX of the component

❤️ Thank you!

2023-08-02 14:07 UTC, fvandenbulcke requested changes

2023-08-02 14:07 UTC, fvandenbulcke commented on src/components/Popover/Popover.ts
> +          <div @click=${this.handleClick} class="popover-cross">${crossIcon}</div>
replace `handleClick` by `closePopOver`

2023-08-02 15:18 UTC, AntonyDerache commented on src/components/Popover/Popover.ts
> +          <div @click=${this.handleClick} class="popover-cross">${crossIcon}</div>
Done

2023-08-04 15:39 UTC, fvandenbulcke approved these changes

2023-08-07 12:29 UTC, Yugo-Cartron approved these changes

2023-08-07 12:31 UTC, merged

2023-08-07 12:32 UTC, Tifloz commented
:tada: This PR is included in version 1.18.0 :tada:

The release is available on:
- [GitHub release](https://github.com/Candy-Doc/candy-doc-components-library/releases/tag/v1.18.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@candy-doc/ui/v/1.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: